[tool.black]
line-length = 110
target_version = ["py38"]
include = '\.pyi?$'
extend-exclude = ''''''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 110
