kind: Service
apiVersion: v1
metadata:
  name: api-staging-nodeport
  annotations:
    "cloud.google.com/app-protocols": '{"https-port":"HTTPS"}'
spec:
  type: NodePort
  selector:
    app: api-staging
  ports:
    - protocol: TCP
      port: 9443
      targetPort: 9443
      name: https-port
